In [1]:
import pandas as pd

In [2]:
df = pd.read_table('botswana.tsv')

In [3]:
df

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,evermarr,agefm,heduc,urban,electric,radio,tv,bicycle
0,0,18,10,catholic,4.0,1.0,1.0,0,NaN,NaN,1,1.0,1.0,1.0,1.0
1,2,43,11,protestant,2.0,1.0,1.0,1,20.0,14.0,1,1.0,1.0,1.0,1.0
2,0,49,4,spirit,4.0,1.0,0.0,1,22.0,1.0,1,1.0,1.0,0.0,0.0
3,0,24,12,other,2.0,1.0,0.0,0,NaN,NaN,1,1.0,1.0,1.0,1.0
4,3,32,13,other,3.0,1.0,1.0,1,24.0,12.0,1,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4356,0,16,7,protestant,2.0,1.0,0.0,0,NaN,NaN,0,0.0,1.0,0.0,0.0
4357,2,28,7,protestant,4.0,1.0,1.0,0,NaN,NaN,0,0.0,1.0,0.0,0.0
4358,4,24,5,protestant,4.0,1.0,1.0,0,NaN,NaN,0,0.0,1.0,0.0,0.0
4359,1,26,0,spirit,5.0,1.0,0.0,1,22.0,7.0,0,0.0,1.0,0.0,0.0
4360,6,36,3,protestant,8.0,1.0,1.0,1,21.0,0.0,0,0.0,1.0,0.0,0.0

In [5]:
df['religion'].value_counts()

spirit        1841
other         1080
protestant     993
catholic       447
Name: religion, dtype: int64

In [6]:
df.dropna()

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,evermarr,agefm,heduc,urban,electric,radio,tv,bicycle
1,2,43,11,protestant,2.0,1.0,1.0,1,20.0,14.0,1,1.0,1.0,1.0,1.0
2,0,49,4,spirit,4.0,1.0,0.0,1,22.0,1.0,1,1.0,1.0,0.0,0.0
4,3,32,13,other,3.0,1.0,1.0,1,24.0,12.0,1,1.0,1.0,1.0,1.0
5,1,30,5,spirit,5.0,1.0,0.0,1,24.0,7.0,1,1.0,0.0,0.0,0.0
6,3,42,4,other,3.0,1.0,0.0,1,15.0,11.0,1,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4353,9,49,0,protestant,5.0,0.0,0.0,1,15.0,0.0,0,0.0,1.0,0.0,0.0
4354,3,31,2,protestant,4.0,1.0,1.0,1,18.0,0.0,0,0.0,1.0,0.0,0.0
4355,4,27,6,protestant,4.0,1.0,1.0,1,17.0,7.0,0,0.0,0.0,0.0,0.0
4359,1,26,0,spirit,5.0,1.0,0.0,1,22.0,7.0,0,0.0,1.0,0.0,0.0
4360,6,36,3,protestant,8.0,1.0,1.0,1,21.0,0.0,0,0.0,1.0,0.0,0.0

In [13]:
df['nevermarr'] = df['agefm'].isnull().astype('int')

In [16]:
cols = ['ceb', 'age', 'educ', 'religion', 'idlnchld', 'knowmeth', 'usemeth',
       'evermarr', 'agefm', 'heduc', 'urban', 'electric', 'radio', 'tv',
       'bicycle', 'nevermarr']

In [17]:
col1 = ['ceb', 'age', 'educ', 'religion', 'idlnchld', 'knowmeth', 'usemeth', 'agefm', 'heduc', 'urban', 'electric', 'radio', 'tv',
       'bicycle', 'nevermarr']

In [19]:
df1 = df[col1]

In [23]:
df1['agefm'].fillna(0, inplace=True)

/var/folders/2d/8s7fzr_974372gjw0dqzc7g00000gn/T/ipykernel_78819/4042172631.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['agefm'].fillna(0, inplace=True)

In [34]:
df1['heduc'] = df1.apply(lambda x: -1 if (pd.isnull(x['heduc']) and x['nevermarr']==1) else x['heduc'], axis=1)

/var/folders/2d/8s7fzr_974372gjw0dqzc7g00000gn/T/ipykernel_78819/22143483.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['heduc'] = df1.apply(lambda x: -1 if (pd.isnull(x['heduc']) and x['nevermarr']==1) else x['heduc'], axis=1)

In [39]:
sum(df1['heduc'].isnull())

123

In [41]:
df1['idlnchld_noans'] = df['idlnchld'].isnull().astype('int')
df1['heduc_noans'] = df['heduc'].isnull().astype('int')
df1['usemeth_noans'] = df['usemeth'].isnull().astype('int')

In [43]:
df1['idlnchld'].fillna(-1, inplace=True)
df1['heduc'].fillna(-2, inplace=True)
df1['usemeth'].fillna(-1, inplace=True)

/var/folders/2d/8s7fzr_974372gjw0dqzc7g00000gn/T/ipykernel_78819/3175952045.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['heduc'].fillna(-2, inplace=True)

In [44]:
df1

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,agefm,heduc,urban,electric,radio,tv,bicycle,nevermarr,idlnchld_noans,heduc_noans,usemeth_noans
0,0,18,10,catholic,4.0,1.0,1.0,0.0,-1.0,1,1.0,1.0,1.0,1.0,1,0,1,0
1,2,43,11,protestant,2.0,1.0,1.0,20.0,14.0,1,1.0,1.0,1.0,1.0,0,0,0,0
2,0,49,4,spirit,4.0,1.0,0.0,22.0,1.0,1,1.0,1.0,0.0,0.0,0,0,0,0
3,0,24,12,other,2.0,1.0,0.0,0.0,-1.0,1,1.0,1.0,1.0,1.0,1,0,1,0
4,3,32,13,other,3.0,1.0,1.0,24.0,12.0,1,1.0,1.0,1.0,1.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4356,0,16,7,protestant,2.0,1.0,0.0,0.0,-1.0,0,0.0,1.0,0.0,0.0,1,0,1,0
4357,2,28,7,protestant,4.0,1.0,1.0,0.0,-1.0,0,0.0,1.0,0.0,0.0,1,0,1,0
4358,4,24,5,protestant,4.0,1.0,1.0,0.0,-1.0,0,0.0,1.0,0.0,0.0,1,0,1,0
4359,1,26,0,spirit,5.0,1.0,0.0,22.0,7.0,0,0.0,1.0,0.0,0.0,0,0,0,0
4360,6,36,3,protestant,8.0,1.0,1.0,21.0,0.0,0,0.0,1.0,0.0,0.0,0,0,0,0

In [46]:
df1.dropna().shape

(4348, 18)

In [47]:
4348* 18

78264

In [49]:
df1.columns

Index(['ceb', 'age', 'educ', 'religion', 'idlnchld', 'knowmeth', 'usemeth',
       'agefm', 'heduc', 'urban', 'electric', 'radio', 'tv', 'bicycle',
       'nevermarr', 'idlnchld_noans', 'heduc_noans', 'usemeth_noans'],
      dtype='object')

In [48]:
import statsmodels.formula.api as smf

In [ ]:
age + educ + religion + idlnchld + knowmeth + usemeth +'\
'agefm + heduc + urban + electric  + bicycle '\
'nevermarr + idlnchld_noans + heduc_noans + usemeth_noans'

In [51]:
m1 = smf.ols('ceb ~ age + educ + religion + idlnchld + knowmeth + usemeth +'\
'agefm + heduc + urban + electric + radio + tv + bicycle +'\
'nevermarr + idlnchld_noans + heduc_noans + usemeth_noans', 
             data=df1)
fitted = m1.fit()
print(fitted.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ceb   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     412.5
Date:                Tue, 19 Apr 2022   Prob (F-statistic):               0.00
Time:                        21:46:51   Log-Likelihood:                -7732.1
No. Observations:                4348   AIC:                         1.550e+04
Df Residuals:                    4328   BIC:                         1.563e+04
Df Model:                          19
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -1.0263      0.212     -4.835      0.000      -1.443      -0.610
religion[T.other]         -0.0830      0.083     -1.001      0.317      -0.245       0.080
religion[T.protestant]    -0.0149      0.082     -0.181      0.857      -0.176       0.146
religion[T.spirit]        -0.0191      0.077     -0.248      0.804      -0.171       0.132
age                        0.1703      0.003     51.891      0.000       0.164       0.177
educ                      -0.0724      0.007     -9.843      0.000      -0.087      -0.058
idlnchld                   0.0760      0.011      6.923      0.000       0.054       0.098
knowmeth                   0.5564      0.121      4.580      0.000       0.318       0.795
usemeth                    0.6473      0.048     13.424      0.000       0.553       0.742
agefm                     -0.0604      0.007     -9.213      0.000      -0.073      -0.048
heduc                     -0.0551      0.008     -6.838      0.000      -0.071      -0.039
urban                     -0.2137      0.047     -4.527      0.000      -0.306      -0.121
electric                  -0.2685      0.077     -3.479      0.001      -0.420      -0.117
radio                     -0.0235      0.051     -0.461      0.645      -0.123       0.076
tv                        -0.1451      0.093     -1.566      0.118      -0.327       0.037
bicycle                    0.2139      0.050      4.260      0.000       0.115       0.312
nevermarr                 -1.3668      0.189     -7.220      0.000      -1.738      -0.996
idlnchld_noans             0.6539      0.153      4.286      0.000       0.355       0.953
heduc_noans               -0.8724      0.145     -6.026      0.000      -1.156      -0.589
usemeth_noans              0.7652      0.196      3.910      0.000       0.382       1.149
==============================================================================
Omnibus:                      224.411   Durbin-Watson:                   1.887
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              859.014
Skew:                           0.003   Prob(JB):                    2.93e-187
Kurtosis:                       5.178   Cond. No.                         369.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [52]:
import statsmodels.stats.api as sms


print('Breusch-Pagan test: p=%f' % sms.het_breuschpagan(fitted.resid, fitted.model.exog)[1])

Breusch-Pagan test: p=0.000000

In [55]:
m2 = smf.ols('ceb ~ age + educ + idlnchld + knowmeth + usemeth +'\
'agefm + heduc + urban + electric + bicycle +'\
'nevermarr + idlnchld_noans + heduc_noans + usemeth_noans', 
             data=df1)
fitted = m2.fit(cov_type='HC1')
print(fitted.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ceb   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     463.7
Date:                Tue, 19 Apr 2022   Prob (F-statistic):               0.00
Time:                        21:52:37   Log-Likelihood:                -7735.7
No. Observations:                4349   AIC:                         1.550e+04
Df Residuals:                    4334   BIC:                         1.560e+04
Df Model:                          14
Covariance Type:                  HC1
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -1.0698      0.258     -4.152      0.000      -1.575      -0.565
age                0.1702      0.004     38.747      0.000       0.162       0.179
educ              -0.0729      0.007    -10.311      0.000      -0.087      -0.059
idlnchld           0.0770      0.014      5.323      0.000       0.049       0.105
knowmeth           0.5611      0.174      3.224      0.001       0.220       0.902
usemeth            0.6515      0.052     12.571      0.000       0.550       0.753
agefm             -0.0606      0.010     -6.192      0.000      -0.080      -0.041
heduc             -0.0573      0.009     -6.440      0.000      -0.075      -0.040
urban             -0.2191      0.045     -4.817      0.000      -0.308      -0.130
electric          -0.3208      0.063     -5.077      0.000      -0.445      -0.197
bicycle            0.2047      0.048      4.284      0.000       0.111       0.298
nevermarr         -1.3648      0.264     -5.173      0.000      -1.882      -0.848
idlnchld_noans     0.6564      0.216      3.043      0.002       0.234       1.079
heduc_noans       -0.8853      0.191     -4.638      0.000      -1.259      -0.511
usemeth_noans      0.7730      0.212      3.639      0.000       0.357       1.189
==============================================================================
Omnibus:                      224.275   Durbin-Watson:                   1.886
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              857.864
Skew:                           0.004   Prob(JB):                    5.21e-187
Kurtosis:                       5.176   Cond. No.                         357.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [56]:

print('Breusch-Pagan test: p=%f' % sms.het_breuschpagan(fitted.resid, fitted.model.exog)[1])

Breusch-Pagan test: p=0.000000

In [59]:
print("F=%f, p=%f, k1=%f" % m1.fit().compare_f_test(m2.fit()))

F=0.767320, p=0.595562, k1=6.000000

In [60]:
m3 = smf.ols('ceb ~ age + educ + idlnchld + knowmeth +'\
'agefm + heduc + urban + electric + bicycle +'\
'nevermarr + idlnchld_noans + heduc_noans', 
             data=df1)
fitted = m3.fit(cov_type='HC1')
print(fitted.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ceb   R-squared:                       0.629
Model:                            OLS   Adj. R-squared:                  0.628
Method:                 Least Squares   F-statistic:                     396.6
Date:                Tue, 19 Apr 2022   Prob (F-statistic):               0.00
Time:                        21:58:44   Log-Likelihood:                -7827.0
No. Observations:                4349   AIC:                         1.568e+04
Df Residuals:                    4336   BIC:                         1.576e+04
Df Model:                          12
Covariance Type:                  HC1
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -1.1932      0.262     -4.563      0.000      -1.706      -0.681
age                0.1776      0.004     41.598      0.000       0.169       0.186
educ              -0.0560      0.007     -7.788      0.000      -0.070      -0.042
idlnchld           0.0705      0.015      4.749      0.000       0.041       0.100
knowmeth           0.8739      0.174      5.029      0.000       0.533       1.214
agefm             -0.0649      0.010     -6.490      0.000      -0.085      -0.045
heduc             -0.0521      0.009     -5.658      0.000      -0.070      -0.034
urban             -0.1866      0.046     -4.018      0.000      -0.278      -0.096
electric          -0.3218      0.065     -4.952      0.000      -0.449      -0.194
bicycle            0.1977      0.048      4.083      0.000       0.103       0.293
nevermarr         -1.5679      0.268     -5.846      0.000      -2.094      -1.042
idlnchld_noans     0.5267      0.225      2.343      0.019       0.086       0.967
heduc_noans       -0.7947      0.195     -4.070      0.000      -1.177      -0.412
==============================================================================
Omnibus:                      250.848   Durbin-Watson:                   1.910
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              937.768
Skew:                          -0.158   Prob(JB):                    2.32e-204
Kurtosis:                       5.253   Cond. No.                         357.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [64]:
print(m2.fit().compare_f_test(m3.fit())[1])

3.0801200123422963e-40